// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum ClientType : sbyte
{
  PLAYER = 0,
  COMMANDER = 1,
  OBSERVER = 2,
  AI = 3,
};


}
