// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ClientStateState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ClientStateState GetRootAsClientStateState(ByteBuffer _bb) { return GetRootAsClientStateState(_bb, new ClientStateState()); }
  public static ClientStateState GetRootAsClientStateState(ByteBuffer _bb, ClientStateState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientStateState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MyFlatBuffer.ClientState State { get { int o = __p.__offset(4); return o != 0 ? (MyFlatBuffer.ClientState)__p.bb.GetSbyte(o + __p.bb_pos) : MyFlatBuffer.ClientState.ENTER; } }

  public static Offset<MyFlatBuffer.ClientStateState> CreateClientStateState(FlatBufferBuilder builder,
      MyFlatBuffer.ClientState state = MyFlatBuffer.ClientState.ENTER) {
    builder.StartTable(1);
    ClientStateState.AddState(builder, state);
    return ClientStateState.EndClientStateState(builder);
  }

  public static void StartClientStateState(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddState(FlatBufferBuilder builder, MyFlatBuffer.ClientState state) { builder.AddSbyte(0, (sbyte)state, 0); }
  public static Offset<MyFlatBuffer.ClientStateState> EndClientStateState(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.ClientStateState>(o);
  }
};


}
