// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum ClientState : sbyte
{
  ENTER = 0,
  EXIT = 1,
  OFFLINE = 2,
};


}
