// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum EquipmentType : sbyte
{
  MAIN = 0,
  SECONDARY = 1,
  GRENADE1 = 2,
  GRENADE2 = 3,
  EXTRA1 = 4,
  EXTRA2 = 5,
  EXTRA3 = 6,
  EXTRA4 = 7,
  ACCESSORY = 8,
};


}
