// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum EventType : sbyte
{
  HOSTAGE = 0,
  FIRE = 1,
  DESTRUCTION = 2,
};


}
