// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct JoinRoomAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static JoinRoomAction GetRootAsJoinRoomAction(ByteBuffer _bb) { return GetRootAsJoinRoomAction(_bb, new JoinRoomAction()); }
  public static JoinRoomAction GetRootAsJoinRoomAction(ByteBuffer _bb, JoinRoomAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinRoomAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint RoomId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ParticipantId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MyFlatBuffer.JoinRoomAction> CreateJoinRoomAction(FlatBufferBuilder builder,
      uint room_id = 0,
      uint participant_id = 0) {
    builder.StartTable(2);
    JoinRoomAction.AddParticipantId(builder, participant_id);
    JoinRoomAction.AddRoomId(builder, room_id);
    return JoinRoomAction.EndJoinRoomAction(builder);
  }

  public static void StartJoinRoomAction(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddRoomId(FlatBufferBuilder builder, uint roomId) { builder.AddUint(0, roomId, 0); }
  public static void AddParticipantId(FlatBufferBuilder builder, uint participantId) { builder.AddUint(1, participantId, 0); }
  public static Offset<MyFlatBuffer.JoinRoomAction> EndJoinRoomAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.JoinRoomAction>(o);
  }
};


}
