// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum MainTask : sbyte
{
  KILL = 0,
  ARREST = 1,
  ARRIVE = 2,
  RESCUE = 3,
  DOUSE = 4,
};


}
