// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum ParticipantRole : sbyte
{
  SWAT = 0,
  FIRST_AID = 1,
  GANGSTER = 2,
  FIRE_CONTROL = 3,
  HOSTAGE = 4,
  PEOPLE = 5,
};


}
