// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ParticipantStatusState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ParticipantStatusState GetRootAsParticipantStatusState(ByteBuffer _bb) { return GetRootAsParticipantStatusState(_bb, new ParticipantStatusState()); }
  public static ParticipantStatusState GetRootAsParticipantStatusState(ByteBuffer _bb, ParticipantStatusState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ParticipantStatusState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MyFlatBuffer.ParticipantStatus Status { get { int o = __p.__offset(4); return o != 0 ? (MyFlatBuffer.ParticipantStatus)__p.bb.GetSbyte(o + __p.bb_pos) : MyFlatBuffer.ParticipantStatus.PENDING; } }
  public uint ParticipantId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RoomId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MyFlatBuffer.ParticipantStatusState> CreateParticipantStatusState(FlatBufferBuilder builder,
      MyFlatBuffer.ParticipantStatus status = MyFlatBuffer.ParticipantStatus.PENDING,
      uint participant_id = 0,
      uint room_id = 0) {
    builder.StartTable(3);
    ParticipantStatusState.AddRoomId(builder, room_id);
    ParticipantStatusState.AddParticipantId(builder, participant_id);
    ParticipantStatusState.AddStatus(builder, status);
    return ParticipantStatusState.EndParticipantStatusState(builder);
  }

  public static void StartParticipantStatusState(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddStatus(FlatBufferBuilder builder, MyFlatBuffer.ParticipantStatus status) { builder.AddSbyte(0, (sbyte)status, 0); }
  public static void AddParticipantId(FlatBufferBuilder builder, uint participantId) { builder.AddUint(1, participantId, 0); }
  public static void AddRoomId(FlatBufferBuilder builder, uint roomId) { builder.AddUint(2, roomId, 0); }
  public static Offset<MyFlatBuffer.ParticipantStatusState> EndParticipantStatusState(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.ParticipantStatusState>(o);
  }
};


}
