// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ParticipantEquipmentAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ParticipantEquipmentAction GetRootAsParticipantEquipmentAction(ByteBuffer _bb) { return GetRootAsParticipantEquipmentAction(_bb, new ParticipantEquipmentAction()); }
  public static ParticipantEquipmentAction GetRootAsParticipantEquipmentAction(ByteBuffer _bb, ParticipantEquipmentAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ParticipantEquipmentAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint ParticipantId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RoomId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MyFlatBuffer.ParticipantEquipmentAction> CreateParticipantEquipmentAction(FlatBufferBuilder builder,
      uint participant_id = 0,
      uint room_id = 0) {
    builder.StartTable(2);
    ParticipantEquipmentAction.AddRoomId(builder, room_id);
    ParticipantEquipmentAction.AddParticipantId(builder, participant_id);
    return ParticipantEquipmentAction.EndParticipantEquipmentAction(builder);
  }

  public static void StartParticipantEquipmentAction(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddParticipantId(FlatBufferBuilder builder, uint participantId) { builder.AddUint(0, participantId, 0); }
  public static void AddRoomId(FlatBufferBuilder builder, uint roomId) { builder.AddUint(1, roomId, 0); }
  public static Offset<MyFlatBuffer.ParticipantEquipmentAction> EndParticipantEquipmentAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.ParticipantEquipmentAction>(o);
  }
};


}
