// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ParticipantWearEquipmentAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ParticipantWearEquipmentAction GetRootAsParticipantWearEquipmentAction(ByteBuffer _bb) { return GetRootAsParticipantWearEquipmentAction(_bb, new ParticipantWearEquipmentAction()); }
  public static ParticipantWearEquipmentAction GetRootAsParticipantWearEquipmentAction(ByteBuffer _bb, ParticipantWearEquipmentAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ParticipantWearEquipmentAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint ParticipantId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RoomId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint EquipmentTypeIndex { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint EquipmentId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MyFlatBuffer.ParticipantWearEquipmentAction> CreateParticipantWearEquipmentAction(FlatBufferBuilder builder,
      uint participant_id = 0,
      uint room_id = 0,
      uint equipment_type_index = 0,
      uint equipment_id = 0) {
    builder.StartTable(4);
    ParticipantWearEquipmentAction.AddEquipmentId(builder, equipment_id);
    ParticipantWearEquipmentAction.AddEquipmentTypeIndex(builder, equipment_type_index);
    ParticipantWearEquipmentAction.AddRoomId(builder, room_id);
    ParticipantWearEquipmentAction.AddParticipantId(builder, participant_id);
    return ParticipantWearEquipmentAction.EndParticipantWearEquipmentAction(builder);
  }

  public static void StartParticipantWearEquipmentAction(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddParticipantId(FlatBufferBuilder builder, uint participantId) { builder.AddUint(0, participantId, 0); }
  public static void AddRoomId(FlatBufferBuilder builder, uint roomId) { builder.AddUint(1, roomId, 0); }
  public static void AddEquipmentTypeIndex(FlatBufferBuilder builder, uint equipmentTypeIndex) { builder.AddUint(2, equipmentTypeIndex, 0); }
  public static void AddEquipmentId(FlatBufferBuilder builder, uint equipmentId) { builder.AddUint(3, equipmentId, 0); }
  public static Offset<MyFlatBuffer.ParticipantWearEquipmentAction> EndParticipantWearEquipmentAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.ParticipantWearEquipmentAction>(o);
  }
};


}
