// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum ParticipantStatus : sbyte
{
  PENDING = 0,
  READY = 1,
};


}
