// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PresetEventSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PresetEventSetting GetRootAsPresetEventSetting(ByteBuffer _bb) { return GetRootAsPresetEventSetting(_bb, new PresetEventSetting()); }
  public static PresetEventSetting GetRootAsPresetEventSetting(ByteBuffer _bb, PresetEventSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PresetEventSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MyFlatBuffer.EventType EventType { get { int o = __p.__offset(4); return o != 0 ? (MyFlatBuffer.EventType)__p.bb.GetSbyte(o + __p.bb_pos) : MyFlatBuffer.EventType.HOSTAGE; } }
  public MyFlatBuffer.Position? Position { get { int o = __p.__offset(6); return o != 0 ? (MyFlatBuffer.Position?)(new MyFlatBuffer.Position()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartPresetEventSetting(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddEventType(FlatBufferBuilder builder, MyFlatBuffer.EventType eventType) { builder.AddSbyte(0, (sbyte)eventType, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<MyFlatBuffer.Position> positionOffset) { builder.AddStruct(1, positionOffset.Value, 0); }
  public static Offset<MyFlatBuffer.PresetEventSetting> EndPresetEventSetting(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.PresetEventSetting>(o);
  }
};


}
