// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PresetTaskSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PresetTaskSetting GetRootAsPresetTaskSetting(ByteBuffer _bb) { return GetRootAsPresetTaskSetting(_bb, new PresetTaskSetting()); }
  public static PresetTaskSetting GetRootAsPresetTaskSetting(ByteBuffer _bb, PresetTaskSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PresetTaskSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MyFlatBuffer.MainTask MainTask { get { int o = __p.__offset(4); return o != 0 ? (MyFlatBuffer.MainTask)__p.bb.GetSbyte(o + __p.bb_pos) : MyFlatBuffer.MainTask.KILL; } }
  public uint KillTarget(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int KillTargetLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetKillTargetBytes() { return __p.__vector_as_span<uint>(6, 4); }
#else
  public ArraySegment<byte>? GetKillTargetBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public uint[] GetKillTargetArray() { return __p.__vector_as_array<uint>(6); }
  public uint DouseTarget(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int DouseTargetLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetDouseTargetBytes() { return __p.__vector_as_span<uint>(8, 4); }
#else
  public ArraySegment<byte>? GetDouseTargetBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public uint[] GetDouseTargetArray() { return __p.__vector_as_array<uint>(8); }
  public MyFlatBuffer.Position? ArrivePosition(int j) { int o = __p.__offset(10); return o != 0 ? (MyFlatBuffer.Position?)(new MyFlatBuffer.Position()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int ArrivePositionLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public uint RescueTarget(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int RescueTargetLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetRescueTargetBytes() { return __p.__vector_as_span<uint>(12, 4); }
#else
  public ArraySegment<byte>? GetRescueTargetBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public uint[] GetRescueTargetArray() { return __p.__vector_as_array<uint>(12); }
  public uint ArrestTarget(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int ArrestTargetLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetArrestTargetBytes() { return __p.__vector_as_span<uint>(14, 4); }
#else
  public ArraySegment<byte>? GetArrestTargetBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public uint[] GetArrestTargetArray() { return __p.__vector_as_array<uint>(14); }
  public MyFlatBuffer.BranchTask? BranchTask(int j) { int o = __p.__offset(16); return o != 0 ? (MyFlatBuffer.BranchTask?)(new MyFlatBuffer.BranchTask()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BranchTaskLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MyFlatBuffer.PresetTaskSetting> CreatePresetTaskSetting(FlatBufferBuilder builder,
      MyFlatBuffer.MainTask main_task = MyFlatBuffer.MainTask.KILL,
      VectorOffset kill_targetOffset = default(VectorOffset),
      VectorOffset douse_targetOffset = default(VectorOffset),
      VectorOffset arrive_positionOffset = default(VectorOffset),
      VectorOffset rescue_targetOffset = default(VectorOffset),
      VectorOffset arrest_targetOffset = default(VectorOffset),
      VectorOffset branch_taskOffset = default(VectorOffset)) {
    builder.StartTable(7);
    PresetTaskSetting.AddBranchTask(builder, branch_taskOffset);
    PresetTaskSetting.AddArrestTarget(builder, arrest_targetOffset);
    PresetTaskSetting.AddRescueTarget(builder, rescue_targetOffset);
    PresetTaskSetting.AddArrivePosition(builder, arrive_positionOffset);
    PresetTaskSetting.AddDouseTarget(builder, douse_targetOffset);
    PresetTaskSetting.AddKillTarget(builder, kill_targetOffset);
    PresetTaskSetting.AddMainTask(builder, main_task);
    return PresetTaskSetting.EndPresetTaskSetting(builder);
  }

  public static void StartPresetTaskSetting(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddMainTask(FlatBufferBuilder builder, MyFlatBuffer.MainTask mainTask) { builder.AddSbyte(0, (sbyte)mainTask, 0); }
  public static void AddKillTarget(FlatBufferBuilder builder, VectorOffset killTargetOffset) { builder.AddOffset(1, killTargetOffset.Value, 0); }
  public static VectorOffset CreateKillTargetVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateKillTargetVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartKillTargetVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDouseTarget(FlatBufferBuilder builder, VectorOffset douseTargetOffset) { builder.AddOffset(2, douseTargetOffset.Value, 0); }
  public static VectorOffset CreateDouseTargetVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDouseTargetVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDouseTargetVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddArrivePosition(FlatBufferBuilder builder, VectorOffset arrivePositionOffset) { builder.AddOffset(3, arrivePositionOffset.Value, 0); }
  public static void StartArrivePositionVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static void AddRescueTarget(FlatBufferBuilder builder, VectorOffset rescueTargetOffset) { builder.AddOffset(4, rescueTargetOffset.Value, 0); }
  public static VectorOffset CreateRescueTargetVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRescueTargetVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartRescueTargetVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddArrestTarget(FlatBufferBuilder builder, VectorOffset arrestTargetOffset) { builder.AddOffset(5, arrestTargetOffset.Value, 0); }
  public static VectorOffset CreateArrestTargetVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateArrestTargetVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartArrestTargetVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBranchTask(FlatBufferBuilder builder, VectorOffset branchTaskOffset) { builder.AddOffset(6, branchTaskOffset.Value, 0); }
  public static VectorOffset CreateBranchTaskVector(FlatBufferBuilder builder, Offset<MyFlatBuffer.BranchTask>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBranchTaskVectorBlock(FlatBufferBuilder builder, Offset<MyFlatBuffer.BranchTask>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartBranchTaskVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MyFlatBuffer.PresetTaskSetting> EndPresetTaskSetting(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.PresetTaskSetting>(o);
  }
};


}
