// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum RobotLevel : sbyte
{
  JUNIOR = 0,
  MIDDLE = 1,
  SENIOR = 2,
};


}
