// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum RobotCharacter : sbyte
{
  NORMAL = 0,
  IRRITABLE = 1,
  SPECIALITY = 2,
  PANIC = 3,
};


}
