// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum RoleSavingState : sbyte
{
  START = 0,
  ABORT = 1,
  DONE = 2,
};


}
