// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum RoleBodyPart : sbyte
{
  HEAD = 0,
  FOOT = 1,
  ARM = 2,
  CHEST = 3,
  LEG = 4,
};


}
