// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct RoleReloadWeaponAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static RoleReloadWeaponAction GetRootAsRoleReloadWeaponAction(ByteBuffer _bb) { return GetRootAsRoleReloadWeaponAction(_bb, new RoleReloadWeaponAction()); }
  public static RoleReloadWeaponAction GetRootAsRoleReloadWeaponAction(ByteBuffer _bb, RoleReloadWeaponAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoleReloadWeaponAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRoleReloadWeaponAction(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MyFlatBuffer.RoleReloadWeaponAction> EndRoleReloadWeaponAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.RoleReloadWeaponAction>(o);
  }
};


}
