// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum RoleLifeType : sbyte
{
  HEALTH = 0,
  SLIGHT = 1,
  MODERATE = 2,
  SEVERE = 3,
  NEARDEATH = 4,
  DEATH = 5,
};


}
