// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct RoleSavingAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static RoleSavingAction GetRootAsRoleSavingAction(ByteBuffer _bb) { return GetRootAsRoleSavingAction(_bb, new RoleSavingAction()); }
  public static RoleSavingAction GetRootAsRoleSavingAction(ByteBuffer _bb, RoleSavingAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoleSavingAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MyFlatBuffer.RoleSavingState State { get { int o = __p.__offset(4); return o != 0 ? (MyFlatBuffer.RoleSavingState)__p.bb.GetSbyte(o + __p.bb_pos) : MyFlatBuffer.RoleSavingState.START; } }

  public static Offset<MyFlatBuffer.RoleSavingAction> CreateRoleSavingAction(FlatBufferBuilder builder,
      MyFlatBuffer.RoleSavingState state = MyFlatBuffer.RoleSavingState.START) {
    builder.StartTable(1);
    RoleSavingAction.AddState(builder, state);
    return RoleSavingAction.EndRoleSavingAction(builder);
  }

  public static void StartRoleSavingAction(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddState(FlatBufferBuilder builder, MyFlatBuffer.RoleSavingState state) { builder.AddSbyte(0, (sbyte)state, 0); }
  public static Offset<MyFlatBuffer.RoleSavingAction> EndRoleSavingAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.RoleSavingAction>(o);
  }
};


}
