// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct RoomListUpdateAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static RoomListUpdateAction GetRootAsRoomListUpdateAction(ByteBuffer _bb) { return GetRootAsRoomListUpdateAction(_bb, new RoomListUpdateAction()); }
  public static RoomListUpdateAction GetRootAsRoomListUpdateAction(ByteBuffer _bb, RoomListUpdateAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoomListUpdateAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MyFlatBuffer.RoomListInfo? List(int j) { int o = __p.__offset(4); return o != 0 ? (MyFlatBuffer.RoomListInfo?)(new MyFlatBuffer.RoomListInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MyFlatBuffer.RoomListUpdateAction> CreateRoomListUpdateAction(FlatBufferBuilder builder,
      VectorOffset listOffset = default(VectorOffset)) {
    builder.StartTable(1);
    RoomListUpdateAction.AddList(builder, listOffset);
    return RoomListUpdateAction.EndRoomListUpdateAction(builder);
  }

  public static void StartRoomListUpdateAction(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddList(FlatBufferBuilder builder, VectorOffset listOffset) { builder.AddOffset(0, listOffset.Value, 0); }
  public static VectorOffset CreateListVector(FlatBufferBuilder builder, Offset<MyFlatBuffer.RoomListInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateListVectorBlock(FlatBufferBuilder builder, Offset<MyFlatBuffer.RoomListInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MyFlatBuffer.RoomListUpdateAction> EndRoomListUpdateAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.RoomListUpdateAction>(o);
  }
};


}
