// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum RoomStatus : sbyte
{
  PENDING = 0,
  RUNNING = 1,
  DONE = 2,
};


}
