// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum RoomType : sbyte
{
  TO_JOIN = 0,
  TO_OBSERVER = 1,
};


}
