// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SyncRoleTransformAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static SyncRoleTransformAction GetRootAsSyncRoleTransformAction(ByteBuffer _bb) { return GetRootAsSyncRoleTransformAction(_bb, new SyncRoleTransformAction()); }
  public static SyncRoleTransformAction GetRootAsSyncRoleTransformAction(ByteBuffer _bb, SyncRoleTransformAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SyncRoleTransformAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSyncRoleTransformAction(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MyFlatBuffer.SyncRoleTransformAction> EndSyncRoleTransformAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.SyncRoleTransformAction>(o);
  }
};


}
