// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SyncRoleMoveTgtAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static SyncRoleMoveTgtAction GetRootAsSyncRoleMoveTgtAction(ByteBuffer _bb) { return GetRootAsSyncRoleMoveTgtAction(_bb, new SyncRoleMoveTgtAction()); }
  public static SyncRoleMoveTgtAction GetRootAsSyncRoleMoveTgtAction(ByteBuffer _bb, SyncRoleMoveTgtAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SyncRoleMoveTgtAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Speed { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public MyFlatBuffer.Vector3? TargetPoint { get { int o = __p.__offset(6); return o != 0 ? (MyFlatBuffer.Vector3?)(new MyFlatBuffer.Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartSyncRoleMoveTgtAction(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSpeed(FlatBufferBuilder builder, float speed) { builder.AddFloat(0, speed, 0.0f); }
  public static void AddTargetPoint(FlatBufferBuilder builder, Offset<MyFlatBuffer.Vector3> targetPointOffset) { builder.AddStruct(1, targetPointOffset.Value, 0); }
  public static Offset<MyFlatBuffer.SyncRoleMoveTgtAction> EndSyncRoleMoveTgtAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.SyncRoleMoveTgtAction>(o);
  }
};


}
