// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TaskStateAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TaskStateAction GetRootAsTaskStateAction(ByteBuffer _bb) { return GetRootAsTaskStateAction(_bb, new TaskStateAction()); }
  public static TaskStateAction GetRootAsTaskStateAction(ByteBuffer _bb, TaskStateAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TaskStateAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartTaskStateAction(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MyFlatBuffer.TaskStateAction> EndTaskStateAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.TaskStateAction>(o);
  }
};


}
