// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum TaskStatus : sbyte
{
  UNDONE = 0,
  DONE = 1,
};


}
