// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct UAVScanningAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static UAVScanningAction GetRootAsUAVScanningAction(ByteBuffer _bb) { return GetRootAsUAVScanningAction(_bb, new UAVScanningAction()); }
  public static UAVScanningAction GetRootAsUAVScanningAction(ByteBuffer _bb, UAVScanningAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UAVScanningAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartUAVScanningAction(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MyFlatBuffer.UAVScanningAction> EndUAVScanningAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyFlatBuffer.UAVScanningAction>(o);
  }
};


}
