// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyFlatBuffer
{

public enum WeaponUseState : sbyte
{
  UNDER_USING = 0,
  STOP_USING = 1,
};


}
